import datetime
from decimal import Decimal

from ibflex import (
    AssetClass,
    BuySell,
    ChangeInDividendAccrual,
    Code,
    OpenClose,
    OrderType,
    Trade,
    TradeType,
)

SELL = Trade(
    transactionType=TradeType.EXCHTRADE,
    openCloseIndicator=OpenClose.CLOSE,
    buySell=BuySell.SELL,
    orderType=OrderType.MARKET,
    assetCategory=AssetClass.STOCK,
    accountId="U123456789",
    currency="USD",
    fxRateToBase=Decimal("0.71453"),
    symbol="STOCKA",
    description="Stock A",
    multiplier=Decimal("1"),
    reportDate=datetime.date(2025, 10, 24),
    tradeDate=datetime.date(2025, 10, 24),
    tradeTime=None,
    settleDateTarget=datetime.date(2025, 10, 27),
    quantity=Decimal("-10"),
    tradePrice=Decimal("25"),
    tradeMoney=Decimal("-250"),
    proceeds=Decimal("250"),
    netCash=Decimal("249"),
    taxes=Decimal("0"),
    ibCommission=Decimal("-1"),
    ibCommissionCurrency="USD",
    closePrice=Decimal("25.66"),
    notes=(),
    cost=Decimal("-308.3008"),
    mtmPnl=Decimal("-6.6"),
    origTradePrice=Decimal("0"),
    levelOfDetail="EXECUTION",
    orderTime=datetime.datetime(2025, 10, 24, 8, 26, 20),
    dateTime=datetime.datetime(2025, 10, 24, 9, 30),
    underlyingSymbol="STOCKA",
    accruedInt=Decimal("0"),
    fineness=Decimal("0.0"),
    weight="0.0",
)

FOREX = Trade(
    transactionType=TradeType.EXCHTRADE,
    openCloseIndicator=None,
    buySell=BuySell.SELL,
    orderType=OrderType.MARKET,
    assetCategory=AssetClass.CASH,
    accountId="U123456789",
    currency="CAD",
    fxRateToBase=Decimal("0.71453"),
    symbol="FOREX",
    description="FOREX",
    multiplier=Decimal("1"),
    reportDate=datetime.date(2025, 10, 24),
    tradeDate=datetime.date(2025, 10, 24),
    settleDateTarget=datetime.date(2025, 10, 24),
    quantity=Decimal("-0.72"),
    tradePrice=Decimal("1.40167"),
    tradeMoney=Decimal("-1.0092024"),
    proceeds=Decimal("1.0092024"),
    netCash=Decimal("0"),
    taxes=Decimal("0"),
    ibCommission=Decimal("0"),
    ibCommissionCurrency="USD",
    closePrice=Decimal("0"),
    cost=Decimal("0"),
    mtmPnl=Decimal("0"),
    origTradePrice=Decimal("0"),
    orderTime=datetime.datetime(2025, 10, 24, 9, 30),
    dateTime=datetime.datetime(2025, 10, 24, 9, 30),
    accruedInt=Decimal("0"),
)

BUYS = [
    Trade(
        transactionType=TradeType.EXCHTRADE,
        openCloseIndicator=None,
        buySell=BuySell.BUY,
        orderType=OrderType.MARKET,
        assetCategory=AssetClass.STOCK,
        accountId="U123456789",
        currency="USD",
        fxRateToBase=Decimal("1"),
        symbol="STOCKB",
        description="STOCK B",
        multiplier=Decimal("1"),
        reportDate=datetime.date(2025, 10, 13),
        tradeDate=datetime.date(2025, 10, 13),
        tradeTime=None,
        settleDateTarget=datetime.date(2025, 10, 14),
        quantity=Decimal("1"),
        tradePrice=Decimal("306.15"),
        tradeMoney=Decimal("306.15"),
        proceeds=Decimal("-306.15"),
        netCash=Decimal("-307.150022"),
        taxes=Decimal("0"),
        ibCommission=Decimal("-1.000022"),
        ibCommissionCurrency="USD",
        closePrice=Decimal("315.47"),
        notes=(),
        cost=Decimal("307.150022"),
        mtmPnl=Decimal("9.32"),
        origTradePrice=Decimal("0"),
        orderTime=datetime.datetime(2025, 10, 11, 14, 56, 23),
        dateTime=datetime.datetime(2025, 10, 13, 9, 30, 1),
        underlyingSymbol="STOCKB",
        accruedInt=Decimal("0"),
    ),
    Trade(
        transactionType=TradeType.EXCHTRADE,
        openCloseIndicator=None,
        buySell=BuySell.BUY,
        orderType=OrderType.LIMIT,
        assetCategory=AssetClass.STOCK,
        accountId="U123456789",
        currency="USD",
        fxRateToBase=Decimal("1"),
        symbol="STOCKB",
        description="STOCK B",
        multiplier=Decimal("1"),
        reportDate=datetime.date(2025, 11, 7),
        tradeDate=datetime.date(2025, 11, 7),
        tradeTime=None,
        settleDateTarget=datetime.date(2025, 11, 10),
        quantity=Decimal("1"),
        tradePrice=Decimal("239.74"),
        tradeMoney=Decimal("239.74"),
        proceeds=Decimal("-239.74"),
        netCash=Decimal("-240.740022"),
        taxes=Decimal("0"),
        ibCommission=Decimal("-1.000022"),
        ibCommissionCurrency="USD",
        closePrice=Decimal("241.93"),
        notes=(),
        cost=Decimal("240.740022"),
        mtmPnl=Decimal("2.19"),
        origTradePrice=Decimal("0"),
        orderTime=datetime.datetime(2025, 11, 7, 14, 40, 47),
        dateTime=datetime.datetime(2025, 11, 7, 14, 41, 1),
        underlyingSymbol="STOCKB",
        accruedInt=Decimal("0"),
    ),
]

NON_BUY_SELL_TRADES = [
    Trade(
        transactionType=TradeType.TRADECANCEL,
        openCloseIndicator=None,
        buySell=BuySell.CANCELBUY,
        orderType=None,
        assetCategory=AssetClass.STOCK,
        accountId="U123456789",
        currency="USD",
        fxRateToBase=Decimal("1"),
        symbol="STOCKB",
        description="STOCK B",
        multiplier=Decimal("1"),
        reportDate=datetime.date(2025, 1, 21),
        tradeDate=datetime.date(2025, 1, 17),
        settleDateTarget=datetime.date(2025, 1, 20),
        quantity=Decimal("-4.4964"),
        tradePrice=Decimal("5.56"),
        tradeMoney=Decimal("-24.999984"),
        proceeds=Decimal("24.999984"),
        netCash=Decimal("24.999984"),
        taxes=Decimal("0"),
        ibCommission=Decimal("0"),
        ibCommissionCurrency="USD",
        closePrice=Decimal("5.4"),
        cost=Decimal("-24.999984"),
        mtmPnl=Decimal("0.7194"),
        origTradePrice=Decimal("5.56"),
        origTradeDate=datetime.date(2025, 1, 17),
        dateTime=datetime.datetime(2025, 1, 17, 12, 38, 35),
    ),
    Trade(
        transactionType=TradeType.TRADECANCEL,
        openCloseIndicator=None,
        buySell=BuySell.CANCELSELL,
        orderType=None,
        assetCategory=AssetClass.STOCK,
        accountId="U123456789",
        currency="USD",
        fxRateToBase=Decimal("1"),
        symbol="STOCKB",
        description="STOCK B",
        multiplier=Decimal("1"),
        reportDate=datetime.date(2025, 1, 21),
        tradeDate=datetime.date(2025, 1, 17),
        settleDateTarget=datetime.date(2025, 1, 20),
        quantity=Decimal("-4.4964"),
        tradePrice=Decimal("5.56"),
        tradeMoney=Decimal("-24.999984"),
        proceeds=Decimal("24.999984"),
        netCash=Decimal("24.999984"),
        taxes=Decimal("0"),
        ibCommission=Decimal("0"),
        ibCommissionCurrency="USD",
        closePrice=Decimal("5.4"),
        cost=Decimal("-24.999984"),
        mtmPnl=Decimal("0.7194"),
        origTradePrice=Decimal("5.56"),
        origTradeDate=datetime.date(2025, 1, 17),
        dateTime=datetime.datetime(2025, 1, 17, 12, 38, 35),
    ),
]

CANCEL_TRADES = [
    Trade(
        transactionType=TradeType.EXCHTRADE,
        openCloseIndicator=None,
        buySell=BuySell.BUY,
        orderType=None,
        assetCategory=AssetClass.STOCK,
        accountId="U123456789",
        currency="USD",
        fxRateToBase=Decimal("1"),
        symbol="STOCKC",
        description="STOCKC",
        multiplier=Decimal("1"),
        tradeID="918942744",
        reportDate=datetime.date(2025, 1, 17),
        tradeDate=datetime.date(2025, 1, 17),
        tradeTime=None,
        settleDateTarget=datetime.date(2025, 1, 20),
        quantity=Decimal("4.4964"),
        tradePrice=Decimal("5.56"),
        tradeMoney=Decimal("24.999984"),
        proceeds=Decimal("-24.999984"),
        netCash=Decimal("-25.250190674"),
        taxes=Decimal("0"),
        ibCommission=Decimal("-0.250206674"),
        ibCommissionCurrency="USD",
        closePrice=Decimal("5.62"),
        notes=(Code.REIMBURSEMENT,),
        cost=Decimal("25.250190674"),
        mtmPnl=Decimal("0.2698"),
        origTradePrice=Decimal("0"),
        origTradeDate=None,
        origTradeID=None,
        origOrderID="0",
        ibOrderID="759609349",
        orderTime=datetime.datetime(2025, 1, 17, 9, 29, 45),
        transactionID="3552864174",
        dateTime=datetime.datetime(2025, 1, 17, 12, 38, 35),
        origTransactionID="0",
    ),
    Trade(
        transactionType=TradeType.TRADECANCEL,
        openCloseIndicator=None,
        buySell=BuySell.CANCELBUY,
        orderType=None,
        assetCategory=AssetClass.STOCK,
        accountId="U123456789",
        currency="USD",
        fxRateToBase=Decimal("1"),
        symbol="STOCKC",
        description="STOCKC",
        multiplier=Decimal("1"),
        tradeID=None,
        reportDate=datetime.date(2025, 1, 21),
        tradeDate=datetime.date(2025, 1, 17),
        tradeTime=None,
        settleDateTarget=datetime.date(2025, 1, 20),
        quantity=Decimal("-4.4964"),
        tradePrice=Decimal("5.56"),
        tradeMoney=Decimal("-24.999984"),
        proceeds=Decimal("24.999984"),
        netCash=Decimal("24.999984"),
        taxes=Decimal("0"),
        ibCommission=Decimal("0"),
        ibCommissionCurrency="USD",
        closePrice=Decimal("5.4"),
        notes=(Code.CANCEL,),
        cost=Decimal("-24.999984"),
        mtmPnl=Decimal("0.7194"),
        origTradePrice=Decimal("5.56"),
        origTradeDate=datetime.date(2025, 1, 17),
        origTradeID="918942744",
        origOrderID="759609349",
        ibOrderID="759609349",
        orderTime=None,
        transactionID="3561087014",
        dateTime=datetime.datetime(2025, 1, 17, 12, 38, 35),
        origTransactionID="3552864174",
    ),
    Trade(
        transactionType=TradeType.EXCHTRADE,
        openCloseIndicator=None,
        buySell=BuySell.BUY,
        orderType=None,
        assetCategory=AssetClass.STOCK,
        accountId="U123456789",
        currency="USD",
        fxRateToBase=Decimal("1"),
        symbol="STOCKC",
        description="STOCKC",
        multiplier=Decimal("1"),
        tradeID="918942744",
        reportDate=datetime.date(2025, 1, 21),
        tradeDate=datetime.date(2025, 1, 17),
        tradeTime=None,
        settleDateTarget=datetime.date(2025, 1, 21),
        quantity=Decimal("4.4964"),
        tradePrice=Decimal("5.56"),
        tradeMoney=Decimal("24.999984"),
        proceeds=Decimal("-24.999984"),
        netCash=Decimal("-24.999984"),
        taxes=Decimal("0"),
        ibCommission=Decimal("0"),
        ibCommissionCurrency="USD",
        closePrice=Decimal("5.4"),
        notes=(Code.REIMBURSEMENT,),
        cost=Decimal("24.999984"),
        mtmPnl=Decimal("-0.7194"),
        origTradePrice=Decimal("0"),
        origTradeDate=None,
        origTradeID=None,
        origOrderID="0",
        ibOrderID="759609349",
        orderTime=datetime.datetime(2025, 1, 17, 9, 29, 45),
        transactionID="3561087015",
        dateTime=datetime.datetime(2025, 1, 17, 12, 38, 35),
        origTransactionID="0",
    ),
]

TRADES = BUYS + [SELL, FOREX] + NON_BUY_SELL_TRADES

DIVIDENDS = [
    ChangeInDividendAccrual(
        date=datetime.date(2025, 12, 3),
        assetCategory=AssetClass.STOCK,
        currency="USD",
        fxRateToBase=Decimal("1"),
        accountId="U123456789",
        symbol="STOCKA",
        description="STOCK A",
        reportDate=datetime.date(2025, 12, 4),
        exDate=datetime.date(2025, 12, 4),
        payDate=datetime.date(2025, 12, 18),
        quantity=Decimal("0.6583"),
        tax=Decimal("0"),
        fee=Decimal("0"),
        grossRate=Decimal("0.09"),
        grossAmount=Decimal("0.06"),
        netAmount=Decimal("0.06"),
        code=(Code.POSTACCRUAL,),
        underlyingSymbol="STOCKA",
        multiplier=Decimal("1"),
        actionID=Decimal("149766144"),
    ),
    ChangeInDividendAccrual(
        date=datetime.date(2025, 12, 18),
        assetCategory=AssetClass.STOCK,
        currency="USD",
        fxRateToBase=Decimal("1"),
        accountId="U123456789",
        symbol="STOCKA",
        description="STOCK A",
        reportDate=datetime.date(2025, 12, 18),
        exDate=datetime.date(2025, 12, 4),
        payDate=datetime.date(2025, 12, 18),
        quantity=Decimal("0.6583"),
        tax=Decimal("0"),
        fee=Decimal("0"),
        grossRate=Decimal("0.09"),
        grossAmount=Decimal("-0.06"),
        netAmount=Decimal("-0.06"),
        code=(Code.REVERSE,),
        underlyingSymbol="STOCKA",
        multiplier=Decimal("1"),
        actionID=Decimal("149766144"),
    ),
]
