import datetime
from decimal import Decimal

from tastytrade.account import Transaction
from tastytrade.order import InstrumentType

trade_buys = [
    Transaction(
        **{
            "id": 100000001,
            "account_number": "1AA00001",
            "transaction_type": "Trade",
            "transaction_sub_type": "Buy to Open",
            "description": "Bought 1 STOCKA @ 40.40",
            "executed_at": datetime.datetime(
                2023, 9, 27, 18, 36, 20, 28000, tzinfo=datetime.timezone.utc
            ),
            "transaction_date": datetime.date(2023, 9, 27),
            "value": Decimal("-40.399"),
            "net_value": Decimal("-40.4"),
            "is_estimated_fee": True,
            "symbol": "STOCKA",
            "instrument_type": InstrumentType.EQUITY,
            "underlying_symbol": "STOCKA",
            "action": "Buy to Open",
            "quantity": Decimal("1.0"),
            "price": Decimal("40.3989"),
            "regulatory_fees": Decimal("0.0"),
            "clearing_fees": Decimal("-0.001"),
            "commission": Decimal("0.0"),
            "proprietary_index_option_fees": Decimal("0.0"),
            "ext_exchange_order_number": "10000000000001",
            "ext_global_order_number": 1001,
            "ext_group_id": "0",
            "ext_group_fill_id": "2000001",
            "ext_exec_id": "300001",
            "exec_id": "99_2000001300001",
            "exchange": "CDE",
            "order_id": 400000001,
            "exchange_affiliation_identifier": "",
            "leg_count": 1,
            "destination_venue": "CITADEL_EQUITIES_B",
            "other_charge": None,
            "other_charge_effect": None,
            "other_charge_description": None,
            "reverses_id": None,
            "cost_basis_reconciliation_date": None,
            "lots": None,
            "agency_price": None,
            "principal_price": None,
        }
    ),
    Transaction(
        **{
            "id": 100000001,
            "account_number": "1AA00001",
            "transaction_type": "Trade",
            "transaction_sub_type": "Buy to Open",
            "description": "Bought 1 STOCKA @ 40.40",
            "executed_at": datetime.datetime(
                2023, 9, 27, 18, 36, 20, 28000, tzinfo=datetime.timezone.utc
            ),
            "transaction_date": datetime.date(2023, 9, 27),
            "value": Decimal("-40.399"),
            "net_value": Decimal("-40.4"),
            "is_estimated_fee": True,
            "symbol": "STOCKB",
            "instrument_type": InstrumentType.EQUITY,
            "underlying_symbol": "STOCKB",
            "action": "Buy to Open",
            "quantity": Decimal("1.0"),
            "price": Decimal("40.3989"),
            "regulatory_fees": Decimal("0.0"),
            "clearing_fees": Decimal("-0.001"),
            "commission": Decimal("0.0"),
            "proprietary_index_option_fees": Decimal("0.0"),
            "ext_exchange_order_number": "10000000000001",
            "ext_global_order_number": 1001,
            "ext_group_id": "0",
            "ext_group_fill_id": "2000001",
            "ext_exec_id": "300001",
            "exec_id": "99_2000001300001",
            "exchange": "CDE",
            "order_id": 400000001,
            "exchange_affiliation_identifier": "",
            "leg_count": 1,
            "destination_venue": "CITADEL_EQUITIES_B",
            "other_charge": None,
            "other_charge_effect": None,
            "other_charge_description": None,
            "reverses_id": None,
            "cost_basis_reconciliation_date": None,
            "lots": None,
            "agency_price": None,
            "principal_price": None,
        }
    ),
    Transaction(
        **{
            "id": 100000001,
            "account_number": "1AA00001",
            "transaction_type": "Trade",
            "transaction_sub_type": "Buy to Open",
            "description": "Bought 1 STOCKA @ 40.40",
            "executed_at": datetime.datetime(
                2024, 7, 20, 10, 0, tzinfo=datetime.timezone.utc
            ),
            "transaction_date": datetime.date(2024, 7, 20),
            "value": Decimal("-40.399"),
            "net_value": Decimal("-40.4"),
            "is_estimated_fee": True,
            "symbol": "STOCKBB",
            "instrument_type": InstrumentType.EQUITY,
            "underlying_symbol": "STOCKBB",
            "action": "Buy to Open",
            "quantity": Decimal("1.0"),
            "price": Decimal("40.3989"),
            "regulatory_fees": Decimal("0.0"),
            "clearing_fees": Decimal("-0.001"),
            "commission": Decimal("0.0"),
            "proprietary_index_option_fees": Decimal("0.0"),
            "ext_exchange_order_number": "10000000000001",
            "ext_global_order_number": 1001,
            "ext_group_id": "0",
            "ext_group_fill_id": "2000001",
            "ext_exec_id": "300001",
            "exec_id": "99_2000001300001",
            "exchange": "CDE",
            "order_id": 400000001,
            "exchange_affiliation_identifier": "",
            "leg_count": 1,
            "destination_venue": "CITADEL_EQUITIES_B",
            "other_charge": None,
            "other_charge_effect": None,
            "other_charge_description": None,
            "reverses_id": None,
            "cost_basis_reconciliation_date": None,
            "lots": None,
            "agency_price": None,
            "principal_price": None,
        }
    ),
]

forward_split = [
    Transaction(
        **{
            "account_number": "1AA00001",
            "action": "Sell to Close",
            "agency_price": None,
            "clearing_fees": None,
            "commission": None,
            "cost_basis_reconciliation_date": None,
            "description": "Forward split: Close 1.0 STOCKA",
            "destination_venue": None,
            "exchange": None,
            "exchange_affiliation_identifier": None,
            "exec_id": None,
            "executed_at": datetime.datetime(
                2023, 9, 28, 18, 36, 20, 28000, tzinfo=datetime.timezone.utc
            ),
            "ext_exchange_order_number": None,
            "ext_exec_id": None,
            "ext_global_order_number": None,
            "ext_group_fill_id": None,
            "ext_group_id": None,
            "id": 100000002,
            "instrument_type": InstrumentType.EQUITY,
            "is_estimated_fee": True,
            "leg_count": None,
            "lots": None,
            "net_value": Decimal("40.4"),
            "order_id": None,
            "other_charge": None,
            "other_charge_description": None,
            "other_charge_effect": None,
            "price": None,
            "principal_price": None,
            "proprietary_index_option_fees": None,
            "quantity": Decimal("1.0"),
            "regulatory_fees": None,
            "reverses_id": None,
            "symbol": "STOCKA",
            "transaction_date": datetime.datetime(2023, 9, 28),
            "transaction_sub_type": "Forward Split",
            "transaction_type": "Receive Deliver",
            "underlying_symbol": "STOCKA",
            "value": Decimal("40.4"),
        }
    ),
    Transaction(
        **{
            "account_number": "1AA00001",
            "action": "Buy to Open",
            "agency_price": None,
            "clearing_fees": None,
            "commission": None,
            "cost_basis_reconciliation_date": None,
            "description": "Forward split: Open 2.0 STOCKA",
            "destination_venue": None,
            "exchange": None,
            "exchange_affiliation_identifier": None,
            "exec_id": None,
            "executed_at": datetime.datetime(
                2023, 9, 28, 18, 36, 21, 28000, tzinfo=datetime.timezone.utc
            ),
            "ext_exchange_order_number": None,
            "ext_exec_id": None,
            "ext_global_order_number": None,
            "ext_group_fill_id": None,
            "ext_group_id": None,
            "id": 100000003,
            "instrument_type": InstrumentType.EQUITY,
            "is_estimated_fee": True,
            "leg_count": None,
            "lots": None,
            "net_value": Decimal("40.4"),
            "order_id": None,
            "other_charge": None,
            "other_charge_description": None,
            "other_charge_effect": None,
            "price": None,
            "principal_price": None,
            "proprietary_index_option_fees": None,
            "quantity": Decimal("2.0"),
            "regulatory_fees": None,
            "reverses_id": None,
            "symbol": "STOCKA",
            "transaction_date": datetime.datetime(2023, 9, 28),
            "transaction_sub_type": "Forward Split",
            "transaction_type": "Receive Deliver",
            "underlying_symbol": "STOCKA",
            "value": Decimal("40.4"),
        }
    ),
]


reverse_split = [
    Transaction(
        **{
            "account_number": "1AA00001",
            "action": "Sell to Close",
            "agency_price": None,
            "clearing_fees": None,
            "commission": None,
            "cost_basis_reconciliation_date": None,
            "description": "Reverse split: Close 4.0 STOCKA",
            "destination_venue": None,
            "exchange": None,
            "exchange_affiliation_identifier": None,
            "exec_id": None,
            "executed_at": datetime.datetime(
                2024, 3, 15, 18, 36, 20, 28000, tzinfo=datetime.timezone.utc
            ),
            "ext_exchange_order_number": None,
            "ext_exec_id": None,
            "ext_global_order_number": None,
            "ext_group_fill_id": None,
            "ext_group_id": None,
            "id": 100000004,
            "instrument_type": InstrumentType.EQUITY,
            "is_estimated_fee": True,
            "leg_count": None,
            "lots": None,
            "net_value": Decimal("161.6"),
            "order_id": None,
            "other_charge": None,
            "other_charge_description": None,
            "other_charge_effect": None,
            "price": None,
            "principal_price": None,
            "proprietary_index_option_fees": None,
            "quantity": Decimal("4.0"),
            "regulatory_fees": None,
            "reverses_id": None,
            "symbol": "STOCKA",
            "transaction_date": datetime.datetime(2024, 3, 15),
            "transaction_sub_type": "Reverse Split",
            "transaction_type": "Receive Deliver",
            "underlying_symbol": "STOCKA",
            "value": Decimal("161.6"),
        }
    ),
    Transaction(
        **{
            "account_number": "1AA00001",
            "action": "Buy to Open",
            "agency_price": None,
            "clearing_fees": None,
            "commission": None,
            "cost_basis_reconciliation_date": None,
            "description": "Reverse split: Open 1.0 STOCKA",
            "destination_venue": None,
            "exchange": None,
            "exchange_affiliation_identifier": None,
            "exec_id": None,
            "executed_at": datetime.datetime(
                2024, 3, 15, 18, 36, 21, 28000, tzinfo=datetime.timezone.utc
            ),
            "ext_exchange_order_number": None,
            "ext_exec_id": None,
            "ext_global_order_number": None,
            "ext_group_fill_id": None,
            "ext_group_id": None,
            "id": 100000005,
            "instrument_type": InstrumentType.EQUITY,
            "is_estimated_fee": True,
            "leg_count": None,
            "lots": None,
            "net_value": Decimal("161.6"),
            "order_id": None,
            "other_charge": None,
            "other_charge_description": None,
            "other_charge_effect": None,
            "price": None,
            "principal_price": None,
            "proprietary_index_option_fees": None,
            "quantity": Decimal("1.0"),
            "regulatory_fees": None,
            "reverses_id": None,
            "symbol": "STOCKA",
            "transaction_date": datetime.datetime(2024, 3, 15),
            "transaction_sub_type": "Reverse Split",
            "transaction_type": "Receive Deliver",
            "underlying_symbol": "STOCKA",
            "value": Decimal("161.6"),
        }
    ),
]


dividends = [
    Transaction(
        **{
            "account_number": "1AA00001",
            "action": None,
            "agency_price": None,
            "clearing_fees": None,
            "commission": None,
            "cost_basis_reconciliation_date": None,
            "description": "COMPANY B",
            "destination_venue": None,
            "exchange": None,
            "exchange_affiliation_identifier": None,
            "exec_id": None,
            "executed_at": datetime.datetime(
                2023, 12, 15, 22, 0, tzinfo=datetime.timezone.utc
            ),
            "ext_exchange_order_number": None,
            "ext_exec_id": None,
            "ext_global_order_number": None,
            "ext_group_fill_id": None,
            "ext_group_id": None,
            "id": 100000002,
            "instrument_type": InstrumentType.EQUITY,
            "is_estimated_fee": True,
            "leg_count": None,
            "lots": None,
            "net_value": Decimal("0.96"),
            "order_id": None,
            "other_charge": None,
            "other_charge_description": None,
            "other_charge_effect": None,
            "price": None,
            "principal_price": None,
            "proprietary_index_option_fees": None,
            "quantity": None,
            "regulatory_fees": None,
            "reverses_id": None,
            "symbol": "STOCKA",
            "transaction_date": datetime.date(2023, 12, 15),
            "transaction_sub_type": "Dividend",
            "transaction_type": "Money Movement",
            "underlying_symbol": "STOCKA",
            "value": Decimal("0.96"),
        }
    ),
    Transaction(
        **{
            "account_number": "1AA00001",
            "action": None,
            "agency_price": None,
            "clearing_fees": None,
            "commission": None,
            "cost_basis_reconciliation_date": None,
            "description": "COMPANY B",
            "destination_venue": None,
            "exchange": None,
            "exchange_affiliation_identifier": None,
            "exec_id": None,
            "executed_at": datetime.datetime(
                2023, 12, 15, 22, 0, tzinfo=datetime.timezone.utc
            ),
            "ext_exchange_order_number": None,
            "ext_exec_id": None,
            "ext_global_order_number": None,
            "ext_group_fill_id": None,
            "ext_group_id": None,
            "id": 100000006,
            "instrument_type": InstrumentType.EQUITY,
            "is_estimated_fee": True,
            "leg_count": None,
            "lots": None,
            "net_value": Decimal("-0.14"),
            "order_id": None,
            "other_charge": None,
            "other_charge_description": None,
            "other_charge_effect": None,
            "price": None,
            "principal_price": None,
            "proprietary_index_option_fees": None,
            "quantity": None,
            "regulatory_fees": None,
            "reverses_id": None,
            "symbol": "STOCKA",
            "transaction_date": datetime.date(2023, 12, 15),
            "transaction_sub_type": "Dividend",
            "transaction_type": "Money Movement",
            "underlying_symbol": "STOCKA",
            "value": Decimal("-0.14"),
        }
    ),
]


dividend_reinvestment_transaction_buy = Transaction(
    **{
        "account_number": "1AA00001",
        "action": "Buy to Open",
        "agency_price": None,
        "clearing_fees": None,
        "commission": None,
        "cost_basis_reconciliation_date": None,
        "description": "Received 0.01391 Long STOCKA via Dividend",
        "destination_venue": None,
        "exchange": None,
        "exchange_affiliation_identifier": None,
        "exec_id": None,
        "executed_at": datetime.datetime(
            2023, 12, 15, 22, 0, tzinfo=datetime.timezone.utc
        ),
        "ext_exchange_order_number": None,
        "ext_exec_id": None,
        "ext_global_order_number": None,
        "ext_group_fill_id": None,
        "ext_group_id": None,
        "id": 100000007,
        "instrument_type": InstrumentType.EQUITY,
        "is_estimated_fee": True,
        "leg_count": None,
        "lots": None,
        "net_value": Decimal("0.0"),
        "order_id": None,
        "other_charge": None,
        "other_charge_description": None,
        "other_charge_effect": None,
        "price": Decimal("59.04"),
        "principal_price": None,
        "proprietary_index_option_fees": None,
        "quantity": Decimal("0.01391"),
        "regulatory_fees": None,
        "reverses_id": None,
        "symbol": "STOCKA",
        "transaction_date": datetime.date(2023, 12, 15),
        "transaction_sub_type": "Dividend",
        "transaction_type": "Receive Deliver",
        "underlying_symbol": "STOCKA",
        "value": Decimal("0.0"),
    }
)


divident_reinvestment = [
    dividend_reinvestment_transaction_buy,
    Transaction(
        **{
            "account_number": "1AA00001",
            "action": None,
            "agency_price": None,
            "clearing_fees": None,
            "commission": None,
            "cost_basis_reconciliation_date": None,
            "description": "Cash dividend reinvested info STOCKA",
            "destination_venue": None,
            "exchange": None,
            "exchange_affiliation_identifier": None,
            "exec_id": None,
            "executed_at": datetime.datetime(
                2023, 12, 15, 22, 0, tzinfo=datetime.timezone.utc
            ),
            "ext_exchange_order_number": None,
            "ext_exec_id": None,
            "ext_global_order_number": None,
            "ext_group_fill_id": None,
            "ext_group_id": None,
            "id": 100000008,
            "instrument_type": InstrumentType.EQUITY,
            "is_estimated_fee": True,
            "leg_count": None,
            "lots": None,
            "net_value": Decimal("0.82"),
            "order_id": None,
            "other_charge": None,
            "other_charge_description": None,
            "other_charge_effect": None,
            "price": None,
            "principal_price": None,
            "proprietary_index_option_fees": None,
            "quantity": None,
            "regulatory_fees": None,
            "reverses_id": None,
            "symbol": "STOCKA",
            "transaction_date": datetime.date(2023, 12, 15),
            "transaction_sub_type": "Withdrawal",
            "transaction_type": "Money Movement",
            "underlying_symbol": "STOCKA",
            "value": Decimal("0.82"),
        }
    ),
]


symbol_change_sell_old = Transaction(
    **{
        "account_number": "1AA00001",
        "action": "Sell to Close",
        "agency_price": None,
        "clearing_fees": None,
        "commission": None,
        "cost_basis_reconciliation_date": None,
        "description": "Symbol change:  Close 5.47124 STOCKB",
        "destination_venue": None,
        "exchange": None,
        "exchange_affiliation_identifier": None,
        "exec_id": None,
        "executed_at": datetime.datetime(
            2024, 7, 15, 10, 0, tzinfo=datetime.timezone.utc
        ),
        "ext_exchange_order_number": None,
        "ext_exec_id": None,
        "ext_global_order_number": None,
        "ext_group_fill_id": None,
        "ext_group_id": None,
        "id": 100000009,
        "instrument_type": InstrumentType.EQUITY,
        "is_estimated_fee": True,
        "leg_count": None,
        "lots": None,
        "net_value": Decimal("82.165"),
        "order_id": None,
        "other_charge": None,
        "other_charge_description": None,
        "other_charge_effect": None,
        "price": None,
        "principal_price": None,
        "proprietary_index_option_fees": None,
        "quantity": Decimal("5.47124"),
        "regulatory_fees": None,
        "reverses_id": None,
        "symbol": "STOCKB",
        "transaction_date": datetime.date(2024, 7, 15),
        "transaction_sub_type": "Symbol Change",
        "transaction_type": "Receive Deliver",
        "underlying_symbol": "STOCKB",
        "value": Decimal("82.165"),
    }
)


symbol_change_buy_new = Transaction(
    **{
        "account_number": "1AA00001",
        "action": "Buy to Open",
        "agency_price": None,
        "clearing_fees": None,
        "commission": None,
        "cost_basis_reconciliation_date": None,
        "description": "Symbol change:  Open 5.47124 STOCKB",
        "destination_venue": None,
        "exchange": None,
        "exchange_affiliation_identifier": None,
        "exec_id": None,
        "executed_at": datetime.datetime(
            2024, 7, 15, 10, 0, tzinfo=datetime.timezone.utc
        ),
        "ext_exchange_order_number": None,
        "ext_exec_id": None,
        "ext_global_order_number": None,
        "ext_group_fill_id": None,
        "ext_group_id": None,
        "id": 100000010,
        "instrument_type": InstrumentType.EQUITY,
        "is_estimated_fee": True,
        "leg_count": None,
        "lots": None,
        "net_value": Decimal("82.165"),
        "order_id": None,
        "other_charge": None,
        "other_charge_description": None,
        "other_charge_effect": None,
        "price": None,
        "principal_price": None,
        "proprietary_index_option_fees": None,
        "quantity": Decimal("5.47124"),
        "regulatory_fees": None,
        "reverses_id": None,
        "symbol": "STOCKBB",
        "transaction_date": datetime.date(2024, 7, 15),
        "transaction_sub_type": "Symbol Change",
        "transaction_type": "Receive Deliver",
        "underlying_symbol": "STOCKBB",
        "value": Decimal("82.165"),
    }
)


TRANSACTIONS = [
    *dividends,
    *divident_reinvestment,
    *forward_split,
    *reverse_split,
    symbol_change_buy_new,
    symbol_change_sell_old,
    *trade_buys,
]
